version: "3"

services:
  api:
    container_name: "process-api"
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=localhost:3306
      - DB_USER=root
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
